title: "Oligo 2021"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Visit Maastricht University":
    - "//maastrichtuniversity.nl"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020-2021 Maastricht University."

color_scheme: foo
