title: "Oligo 2021"
remote_theme: oligo2021/just-the-docs
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Visit Maastricht University":
    - "//maastrichtuniversity.nl"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2020-2021 Maastricht University."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme
color_scheme: foo
